# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# All rights reserved.

# TODO: Edit pubspec.yaml

name: dictosaurus
description: Extensions on String that provide dictionary and thesaurus functions (**PRE-RELEASE**).
version: 0.0.1-beta.5
repository: https://github.com/GM-Consult-Pty-Ltd/dictosaurus
homepage: https://github.com/GM-Consult-Pty-Ltd
issue_tracker: https://github.com/GM-Consult-Pty-Ltd/dictosaurus/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  # -----PubDev Packages (in alphabetic order) -----
  collection: ^1.16.0
  meta: ^1.8.0
  text_indexing: ^0.16.0


dev_dependencies:
  gmconsult_dev: ^0.0.4
  hive: ^2.2.3
  lints: ^2.0.0
  test: ^1.21.1
