# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# All rights reserved.

# TODO: Edit pubspec.yaml

name: dart_package_template
description: TODO - A short description of your package.
version: 0.0.1-beta.1
repository: https://github.com/GM-Consult-Pty-Ltd/dart_package_template
homepage: https://github.com/GM-Consult-Pty-Ltd
issue_tracker: https://github.com/GM-Consult-Pty-Ltd/dart_package_template/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  # -----PubDev Packages (in alphabetic order) -----

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
