# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# All rights reserved.

# TODO: Edit pubspec.yaml

name: dictosaurus
description: Extensions on String that provide dictionary and thesaurus functions.
version: 0.0.1-beta.2
repository: https://github.com/GM-Consult-Pty-Ltd/dictosaurus
homepage: https://github.com/GM-Consult-Pty-Ltd
issue_tracker: https://github.com/GM-Consult-Pty-Ltd/dictosaurus/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  # -----PubDev Packages (in alphabetic order) -----

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
