# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# All rights reserved.

name: dictosaurus
description: Dictionary, thesaurus and term expansion utilities used in natural language processing.
version: 0.0.10+1
repository: https://github.com/GM-Consult-Pty-Ltd/dictosaurus
homepage: https://github.com/GM-Consult-Pty-Ltd
issue_tracker: https://github.com/GM-Consult-Pty-Ltd/dictosaurus/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  collection: ^1.16.0
  gmconsult_dart_core: ^0.0.5
  meta: ^1.8.0
  text_analysis: ^0.16.0

dev_dependencies:
  gmconsult_dev: ^0.0.7+4
  gmconsult_proprietary: 
    version: ^0.0.1-5
    hosted: https://onepub.dev/api/jxxxpsdavu
  hive: ^2.2.3
  lints: ^2.0.0
  test: ^1.21.1
  text_indexing: ^0.16.0
